version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user_management_db
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  # Backend service (Spring Boot)
  springboot-app:
    image: my_backend_image:tag-v1
    container_name: springboot-container
    environment:
      # Database Configuration
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: user_management_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456

      # Server Configuration
      SERVER_PORT: 9999
      SERVER_VERSION: 1.0.0
      ALLOWED_ORIGIN: "http://localhost:6789"

      # JPA Configuration
      JPA_DDL_AUTO: "update"
      JPA_SHOW_SQL: "true"

      # Security Configuration
      JWT_SECRET: "dGV5cjgzNWlsNWhjYXl1d2hsYXpkaGZ5dmxhd3NkbXlrZmdhbW84cThyNmhxOG01c2RscGQ3M2VrdG1uYnFnZWtybjVwYzEzNGs4Zjc5dmlqbGJrYjh2OHdyYnEyc3BsOWUxbnkwbzh4dmtjano1dmpjYWFxM3UybGFrcWg5czM="

    ports:
      - "9999:9999"
    depends_on:
      - mysql
